### ISSUE TITLE
Gamecontroller hasn't focus on mupen64plus

### ISSUE THREAD

**Issue by chrisdecker1201** [maloep/romcollectionbrowser#284] opened 2017-07-15 15:19 UTC
Hello,

I'm running an Ubuntu Server 16.04 (LTS) with Kodi 17.3 and RCB 2.1.2. Also I installed mupen64plus in Version 2.5.0

I have no problems controlling Kodi via the Gamecontroller (Gasia Co.,Ltd PS(R) Gamepad) but when I start Mario Kart 64 via RCB the game starts in fullscreen and I can't control the game via Keyboard or Gamecontroller. I found out when I kill the mupen64plus process, that all inputs was controlling the Kodi in the background. 

It seems like Kodi has the focus on the input and not mupen64plus.

Maybe someone can help me.

**Comment by maloep** [comment] 2018-01-03 16:11
Best solution would be to launch the emulator in solo mode.

**Comment by chrisdecker1201** [comment] 2018-01-03 17:35
I've hope that maybe with Kodi 18 (https://github.com/xbmc/xbmc/pull/12367) this issue is solved.

**Comment by maloep** [comment] 2018-01-03 18:10
Yes, games launched via RetroPlayer should not have these issues. But afaik, N64 will not be supported at the beginning. There needs to be OpenGL support which is implemented in an experimental branch and won't be ready for Kodi 18.

Have you tried solo mode?

**Comment by chrisdecker1201** [comment] 2018-01-04 17:37
I've tried it but than the game isn't started. Only a text on the screen "starting ..." something appears and nothing happens. Maybe I just wait for the RetroPlayer or would you like to have some log-files?

**Comment by maloep** [comment] 2018-01-04 18:06
Did you follow these instructions?
https://github.com/maloep/romcollectionbrowser/wiki/LaunchGames#launch-games-in-solo-mode
https://github.com/maloep/romcollectionbrowser/wiki/FAQ#launching-games-does-not-work-on-system-x-with-emulator-y

If so, you can upload a log and I will see if there is any relevant error.

**Comment by chrisdecker1201** [comment] 2018-01-06 08:15
I've tried it but without sucess. Screen goes black, Kodi restart but with another resolution and with a grayish look.

Here a log file
`
09:09:44.166 T:140035860760960  NOTICE: special://profile/ is mapped to: special://masterprofile/
09:09:44.166 T:140035860760960  NOTICE: -----------------------------------------------------------------------
09:09:44.166 T:140035860760960  NOTICE: Starting Kodi (17.6 Git:20171114-a9a7a20). Platform: Linux x86 64-bit
09:09:44.166 T:140035860760960  NOTICE: Using Release Kodi x64 build
09:09:44.166 T:140035860760960  NOTICE: Kodi compiled Nov  4 2012 by GCC 5.4.0 for Linux x86 64-bit version 4.4.90 (263258)
09:09:44.166 T:140035860760960  NOTICE: Running on Ubuntu 16.04.3 LTS, kernel: Linux x86 64-bit version 4.4.0-96-generic
09:09:44.166 T:140035860760960  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
09:09:44.166 T:140035860760960  NOTICE: Host CPU: Intel(R) Pentium(R) CPU G4400 @ 3.30GHz, 2 cores available
09:09:44.166 T:140035860760960  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi
09:09:44.166 T:140035860760960  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/x86_64-linux-gnu/kodi
09:09:44.166 T:140035860760960  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib/x86_64-linux-gnu/kodi/addons
09:09:44.166 T:140035860760960  NOTICE: special://masterprofile/ is mapped to: /home/kodi/.kodi/userdata
09:09:44.166 T:140035860760960  NOTICE: special://envhome/ is mapped to: /home/kodi
09:09:44.166 T:140035860760960  NOTICE: special://home/ is mapped to: /home/kodi/.kodi
09:09:44.166 T:140035860760960  NOTICE: special://temp/ is mapped to: /home/kodi/.kodi/temp
09:09:44.166 T:140035860760960  NOTICE: special://logpath/ is mapped to: /home/kodi/.kodi/temp
09:09:44.166 T:140035860760960  NOTICE: The executable running is: /usr/lib/x86_64-linux-gnu/kodi/kodi.bin
09:09:44.166 T:140035860760960  NOTICE: Local hostname: decker-server
09:09:44.166 T:140035860760960  NOTICE: Log File is located: /home/kodi/.kodi/temp//kodi.log
09:09:44.166 T:140035860760960  NOTICE: -----------------------------------------------------------------------
09:09:44.181 T:140035860760960   ERROR: DBus: Error org.freedesktop.DBus.Error.InvalidArgs - No such property 'OnLowBattery'
09:09:44.183 T:140035860760960   ERROR: DBus: Error org.freedesktop.DBus.Error.InvalidArgs - No such property 'CanSuspend'
09:09:44.183 T:140035860760960   ERROR: DBus: Error org.freedesktop.DBus.Error.InvalidArgs - No such property 'CanHibernate'
09:09:44.184 T:140035860760960  NOTICE: load settings...
09:09:44.225 T:140035860760960  NOTICE: Found 1 Lists of Devices
09:09:44.225 T:140035860760960  NOTICE: Enumerated ALSA devices:
09:09:44.225 T:140035860760960  NOTICE:     Device 1
09:09:44.225 T:140035860760960  NOTICE:         m_deviceName      : @
09:09:44.225 T:140035860760960  NOTICE:         m_displayName     : Default (HDA Intel PCH HDMI 0)
09:09:44.225 T:140035860760960  NOTICE:         m_displayNameExtra:
09:09:44.225 T:140035860760960  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
09:09:44.225 T:140035860760960  NOTICE:         m_channels        : FL,FR,LFE,FC,BC,BL,BR,FLOC,FROC,BLOC,BROC,TFC,TC,TFL,TFR,UNKNOWN1
09:09:44.225 T:140035860760960  NOTICE:         m_sampleRates     : 48000
09:09:44.225 T:140035860760960  NOTICE:         m_dataFormats     : AE_FMT_S32NE
09:09:44.225 T:140035860760960  NOTICE:         m_streamTypes     : No passthrough capabilities
09:09:44.225 T:140035860760960  NOTICE:     Device 2
09:09:44.225 T:140035860760960  NOTICE:         m_deviceName      : @:CARD=PCH,DEV=0
09:09:44.225 T:140035860760960  NOTICE:         m_displayName     : HDA Intel PCH
09:09:44.225 T:140035860760960  NOTICE:         m_displayNameExtra: HDMI 0
09:09:44.225 T:140035860760960  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
09:09:44.225 T:140035860760960  NOTICE:         m_channels        : FL,FR
09:09:44.225 T:140035860760960  NOTICE:         m_sampleRates     : 48000
09:09:44.225 T:140035860760960  NOTICE:         m_dataFormats     : AE_FMT_S32NE
09:09:44.225 T:140035860760960  NOTICE:         m_streamTypes     : No passthrough capabilities
09:09:44.225 T:140035860760960  NOTICE:     Device 3
09:09:44.225 T:140035860760960  NOTICE:         m_deviceName      : hdmi:CARD=PCH,DEV=0
09:09:44.225 T:140035860760960  NOTICE:         m_displayName     : HDA Intel PCH
09:09:44.225 T:140035860760960  NOTICE:         m_displayNameExtra: PHL PhilipsTV (5) on HDMI #0
09:09:44.225 T:140035860760960  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
09:09:44.225 T:140035860760960  NOTICE:         m_channels        : FL,FR,LFE,FC,BL,BR,BC,BLOC,BROC
09:09:44.225 T:140035860760960  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
09:09:44.225 T:140035860760960  NOTICE:         m_dataFormats     : AE_FMT_RAW,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
09:09:44.225 T:140035860760960  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
09:09:44.225 T:140035860760960  NOTICE:     Device 4
09:09:44.225 T:140035860760960  NOTICE:         m_deviceName      : hdmi:CARD=PCH,DEV=1
09:09:44.225 T:140035860760960  NOTICE:         m_displayName     : HDA Intel PCH
09:09:44.225 T:140035860760960  NOTICE:         m_displayNameExtra: HDMI #1
09:09:44.225 T:140035860760960  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
09:09:44.225 T:140035860760960  NOTICE:         m_channels        : FL,FR,LFE,FC,BC,BL,BR,FLOC,FROC,BLOC,BROC,TFC,TC,TFL,TFR,UNKNOWN1
09:09:44.225 T:140035860760960  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
09:09:44.225 T:140035860760960  NOTICE:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
09:09:44.225 T:140035860760960  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
09:09:44.225 T:140035860760960  NOTICE:     Device 5
09:09:44.225 T:140035860760960  NOTICE:         m_deviceName      : hdmi:CARD=PCH,DEV=2
09:09:44.225 T:140035860760960  NOTICE:         m_displayName     : HDA Intel PCH
09:09:44.225 T:140035860760960  NOTICE:         m_displayNameExtra: HDMI #2
09:09:44.225 T:140035860760960  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
09:09:44.225 T:140035860760960  NOTICE:         m_channels        : FL,FR,LFE,FC,BC,BL,BR,FLOC,FROC,BLOC,BROC,TFC,TC,TFL,TFR,UNKNOWN1
09:09:44.225 T:140035860760960  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
09:09:44.225 T:140035860760960  NOTICE:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
09:09:44.225 T:140035860760960  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
09:09:44.227 T:140035860760960  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
09:09:44.227 T:140035860760960  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
09:09:44.227 T:140035860760960  NOTICE: Default Video Player: VideoPlayer
09:09:44.227 T:140035860760960  NOTICE: Default Audio Player: paplayer
09:09:44.227 T:140035860760960  NOTICE: Disabled debug logging due to GUI setting. Level 0.
09:09:44.227 T:140035860760960  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
09:09:44.227 T:140035860760960  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
09:09:44.227 T:140035860760960  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
09:09:44.227 T:140035860760960  NOTICE: Loaded playercorefactory configuration
09:09:44.227 T:140035860760960  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
09:09:44.227 T:140035860760960  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
09:09:44.230 T:140035860760960  NOTICE: Running database version Addons27
09:09:44.242 T:140035860760960  NOTICE: ADDONS: Using repository repository.xbmc.org
09:09:44.416 T:140035860760960  NOTICE: Checking resolution 16
09:09:44.476 T:140035860760960  NOTICE: Using visual 0x20
09:09:44.478 T:140035860760960  NOTICE: GL_VENDOR = Intel Open Source Technology Center
09:09:44.478 T:140035860760960  NOTICE: GL_RENDERER = Mesa DRI Intel(R) HD Graphics 510 (Skylake GT1)
09:09:44.478 T:140035860760960  NOTICE: GL_VERSION = 3.0 Mesa 17.2.4
09:09:44.479 T:140035860760960  NOTICE: GL_SHADING_LANGUAGE_VERSION = 1.30
09:09:44.479 T:140035860760960  NOTICE: GL_EXTENSIONS = GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_3DFX_texture_compression_FXT1 GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_APPLE_object_purgeable GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_texture_barrier GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_program_interface_query GL_ARB_robust_buffer_access_behavior GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_INTEL_performance_query GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_texture_barrier GL_ARB_transform_feedback_overflow_query GL_EXT_polygon_offset_clamp GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_ARB_shader_atomic_counter_ops GL_ARB_shader_ballot GL_ARB_shader_clock GL_EXT_shader_samples_identical GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_MESA_shader_integer_functions
09:09:44.583 T:140035261200128  NOTICE: Running database version Addons27
09:09:44.584 T:140035261200128  NOTICE: Running database version ViewModes6
09:09:44.584 T:140035261200128  NOTICE: Running database version Textures13
09:09:44.585 T:140035261200128  NOTICE: Running database version MyMusic60
09:09:44.587 T:140035261200128  NOTICE: Running database version MyVideos107
09:09:44.588 T:140035261200128  NOTICE: Running database version TV29
09:09:44.589 T:140035261200128  NOTICE: Running database version Epg11
09:09:44.591 T:140035860760960  NOTICE: start dvd mediatype detection
09:09:44.610 T:140034869856000   ERROR: AddOnLog: Joystick Support: Device "Sony Interactive Entertainment Wireless Controller": can't find <controller> tag
09:09:44.638 T:140034869856000  NOTICE: Register - new joystick device registered on addon->peripheral.joystick/0: Gasia Co.,Ltd PS(R) Gamepad
09:09:44.686 T:140035860760960 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
09:09:44.745 T:140035860760960  NOTICE: initialize done
09:09:44.745 T:140035860760960  NOTICE: Running the application...
09:09:44.747 T:140035860760960  NOTICE: starting zeroconf publishing
09:09:44.747 T:140035860760960  NOTICE: CWebServer[8099]: Started
09:09:44.747 T:140035860760960  NOTICE: starting upnp client
09:09:44.759 T:140035860760960   ERROR: JSONRPC Server: Failed to bind ipv4 serversocket
09:09:44.759 T:140034028062464  NOTICE: ES: Starting UDP Event server on port 9777
09:09:44.759 T:140034028062464  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
09:09:45.089 T:140035252807424  NOTICE: Found 1 Lists of Devices
09:09:45.089 T:140035252807424  NOTICE: Enumerated ALSA devices:
09:09:45.089 T:140035252807424  NOTICE:     Device 1
09:09:45.089 T:140035252807424  NOTICE:         m_deviceName      : @
09:09:45.089 T:140035252807424  NOTICE:         m_displayName     : Default (HDA Intel PCH HDMI 0)
09:09:45.089 T:140035252807424  NOTICE:         m_displayNameExtra:
09:09:45.089 T:140035252807424  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
09:09:45.089 T:140035252807424  NOTICE:         m_channels        : FL,FR,LFE,FC,BC,BL,BR,FLOC,FROC,BLOC,BROC,TFC,TC,TFL,TFR,UNKNOWN1
09:09:45.089 T:140035252807424  NOTICE:         m_sampleRates     : 48000
09:09:45.089 T:140035252807424  NOTICE:         m_dataFormats     : AE_FMT_S32NE
09:09:45.089 T:140035252807424  NOTICE:         m_streamTypes     : No passthrough capabilities
09:09:45.089 T:140035252807424  NOTICE:     Device 2
09:09:45.089 T:140035252807424  NOTICE:         m_deviceName      : @:CARD=PCH,DEV=0
09:09:45.089 T:140035252807424  NOTICE:         m_displayName     : HDA Intel PCH
09:09:45.089 T:140035252807424  NOTICE:         m_displayNameExtra: HDMI 0
09:09:45.089 T:140035252807424  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
09:09:45.089 T:140035252807424  NOTICE:         m_channels        : FL,FR
09:09:45.089 T:140035252807424  NOTICE:         m_sampleRates     : 48000
09:09:45.089 T:140035252807424  NOTICE:         m_dataFormats     : AE_FMT_S32NE
09:09:45.089 T:140035252807424  NOTICE:         m_streamTypes     : No passthrough capabilities
09:09:45.089 T:140035252807424  NOTICE:     Device 3
09:09:45.089 T:140035252807424  NOTICE:         m_deviceName      : hdmi:CARD=PCH,DEV=0
09:09:45.089 T:140035252807424  NOTICE:         m_displayName     : HDA Intel PCH
09:09:45.089 T:140035252807424  NOTICE:         m_displayNameExtra: PHL PhilipsTV (5) on HDMI #0
09:09:45.089 T:140035252807424  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
09:09:45.089 T:140035252807424  NOTICE:         m_channels        : FL,FR,LFE,FC,BL,BR,BC,BLOC,BROC
09:09:45.089 T:140035252807424  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
09:09:45.089 T:140035252807424  NOTICE:         m_dataFormats     : AE_FMT_RAW,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
09:09:45.089 T:140035252807424  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
09:09:45.089 T:140035252807424  NOTICE:     Device 4
09:09:45.089 T:140035252807424  NOTICE:         m_deviceName      : hdmi:CARD=PCH,DEV=1
09:09:45.089 T:140035252807424  NOTICE:         m_displayName     : HDA Intel PCH
09:09:45.089 T:140035252807424  NOTICE:         m_displayNameExtra: HDMI #1
09:09:45.089 T:140035252807424  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
09:09:45.089 T:140035252807424  NOTICE:         m_channels        : FL,FR,LFE,FC,BC,BL,BR,FLOC,FROC,BLOC,BROC,TFC,TC,TFL,TFR,UNKNOWN1
09:09:45.089 T:140035252807424  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
09:09:45.089 T:140035252807424  NOTICE:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
09:09:45.089 T:140035252807424  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
09:09:45.089 T:140035252807424  NOTICE:     Device 5
09:09:45.089 T:140035252807424  NOTICE:         m_deviceName      : hdmi:CARD=PCH,DEV=2
09:09:45.089 T:140035252807424  NOTICE:         m_displayName     : HDA Intel PCH
09:09:45.089 T:140035252807424  NOTICE:         m_displayNameExtra: HDMI #2
09:09:45.089 T:140035252807424  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
09:09:45.089 T:140035252807424  NOTICE:         m_channels        : FL,FR,LFE,FC,BC,BL,BR,FLOC,FROC,BLOC,BROC,TFC,TC,TFL,TFR,UNKNOWN1
09:09:45.089 T:140035252807424  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
09:09:45.089 T:140035252807424  NOTICE:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
09:09:45.089 T:140035252807424  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
09:09:45.407 T:140033948436224  NOTICE: Start - EPG thread started
09:09:45.557 T:140034534831872  NOTICE: [plugin.video.youtube] Startup: detected Krypton (Kodi-17.6), setting DASH_SUPPORT_BUILTIN = False, DASH_SUPPORT_ADDON = True
09:09:46.651 T:140033859344128 WARNING: CPythonInvoker(4): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
09:09:46.802 T:140033859344128 WARNING: CSkinInfo: failed to load skin settings
09:09:47.149 T:140035860760960 WARNING: Trying to add unsupported control type 1
09:09:47.169 T:140035860760960 WARNING: Previous line repeats 1 times.
09:09:47.169 T:140035860760960   ERROR: Control 500 in window 13000 has been asked to focus, but it can't

`

**Comment by maloep** [comment] 2018-01-07 07:25
Sorry, there is no RCB logging in there. You need to enable Debug logging in kodi settings to get addons logging information.

If you enable solo mode I will need both log files: kodi.log and kodi.old.log. You can just copy/paste the complete files here (really the files, not the content).

Do you have other emulators working? Maybe you could try retroarch with the mupen64 core and see if this will solve the issue. For me it is running well (but I am on Windows, not Linux).

**Comment by chrisdecker1201** [comment] 2018-01-08 18:30
I've no other emulators working. Sorry. If I've time I will try retroarch.

Here the files with debug logging.
[kodi.log](https://github.com/maloep/romcollectionbrowser/files/1612606/kodi.log)
[kodi.old.log](https://github.com/maloep/romcollectionbrowser/files/1612607/kodi.old.log)

**Comment by maloep** [comment] 2018-01-09 16:20
Something went wrong with these log files. Kodi.old.log seems to be the file when RCB comes back after launching in solo mode. In kodi.log there is no RCB running at all.

You should do the following steps:
- set Kodi to debug logging
- launch a game in solo mode
- wait for kodi and RCB restarting
- close kodi (and don't restart it - if it restarts automatically on your system, don't close it)
- grab kodi.log and kodi.old.log and put them here

You can check if you have the correct log files by searching for the string "RCB_INFO: cmd:" in kodi.old.log. There you should find the complete command that RCB sends to the shell.

**Comment by chrisdecker1201** [comment] 2018-01-14 06:06
I did what you described. Kodi restart, but there is no RCB_INFO: cmd in the log-file...

**Comment by maloep** [comment] 2018-01-16 15:45
Absolutely strange. No "RCB" entries at all?
I am sorry, but I can't help you any further without any log information.

As suggested above you could try Retroarch or wait for mupen64-support in RetroPlayer (as garbear stated, they are not far away: https://forum.kodi.tv/showthread.php?tid=327161)

**Comment by maloep** [comment] 2018-01-18 15:25
Just one more thing: while I was debugging a launch issue myself I found out that the string to search for is "RCB_INFO cmd:" (without : after RCB_INFO). Maybe this mislead you.

**Comment by maloep** [comment] 2018-07-15 10:09
Not reproducable in my setup. Sorry.

**Closed by maloep** 2018-07-15 10:09 UTC
Labels: bug
