### ISSUE TITLE
platform_libraries are not installed on Kodi, XBian 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [maloep/romcollectionbrowser#214] opened 2015-04-23 09:17 UTC
```
What steps will reproduce the problem?
.7z files as roms

I am using this version of Linux xbian 3.18.8+ #1 SMP PREEMPT Thu Mar 5 
03:13:36 CET 2015 armv7l GNU/Linux (downloaded the stable release today)

It was a mint installation and I only installed the RCB addon.
I have a 7z compressed rom and try to launch it.
In the log I get the error that the the library py7zlib is missing.


```

Original issue reported on code.google.com by `huehnerb...@googlemail.com` on 2 Apr 2015 at 1:12

**Comment by bruny** [comment] 2016-06-26 12:19
Likely duplicate of #186

**Closed** 2018-01-03 14:34 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
