### ISSUE TITLE
Error about control id

### ISSUE THREAD

**Issue by Kupo91** [maloep/romcollectionbrowser#401] opened 2019-04-19 18:32 UTC
I refer this bugreport to https://forum.kodi.tv/showthread.php?tid=70115&pid=2838193#pid2838193
I only had this one time but a bug is a bug which might want to be fixed.
So if I remember correctly I opend RCB and got an error something about a xml file. I guess it had something with "window" and "home" in its name. And something about "control". Anyway I got a white screen and my controller didnt work anymore and so did my keyboard. The only button which luckily brought me out of this was the home button.
Here is a logfile but it doesnt seem to include much about this error.
[01_KODI.log](https://github.com/maloep/romcollectionbrowser/files/3098985/01_KODI.log)

**Comment by maloep** [comment] 2019-07-31 15:18
Sorry, there is no useful information in the log file. (By default addon logging is disabled in Kodi).

So I guess it will be hard to reproduce this error with a proper log file. I will leave this issue open for a while. If you are able to give me a log with relevant information I will have a chance to look into it.

**Comment by Kupo91** [comment] 2019-08-01 07:55
Das ist auch nur ein mal passiert, und zwar als ich Kodi und alles neuinstalliert hab. Damals wusste ich nicht, wodurch dieser Whitescreen verursacht wurde. Erst als jemand im Forum geschrieben hat, dass er das auch hatte, ist mir klar geworden, dass es mit RCB zu tun hat.

**Comment by maloep** [comment] 2019-08-02 06:29
Ok, then I know what you mean. I had the same issues when I installed Kodi and RCB for the first time on my new PC. Honestly, I just ignored it. But you are right, it might be worth to look into it.

**Comment by Kupo91** [comment] 2020-05-12 18:30
I now have this issue again and this time it doesnt fix itself :/ Even if I didnt change anything. Just a few hours ago it worked fine. Now I cant get it running anymore. I just tested it for 3 times (with kodi restarts) but it seems to be broken.

This it the screen that I get:
![screenshot000](https://user-images.githubusercontent.com/41426906/81731463-3fcf3600-948f-11ea-96b7-3c3335d08f40.jpg)

And here is my logfile:
[01_KODI.log](https://github.com/maloep/romcollectionbrowser/files/4617744/01_KODI.log)

**Comment by maloep** [comment] 2020-05-13 06:30
Ok, I think I can reproduce it somehow. But for me it works when I restart RCB.

How do you quit RCB?
I can reproduce this error when I open RCB and then go back to Kodis Homescreen without "quitting" RCB. In this case RCB can't save its last selected control id and then tries to load a control with id 0 at next start. But as soon as I quit RCB it will work correctly when I restart it.

Can you check your settings.xml file in RCBs userdata directory?
Is there a line looking like this?
<setting id="rcb_view_mode" default="true"></setting>

If so, try to change it to this:
<setting id="rcb_view_mode">50</setting>

**Comment by Kupo91** [comment] 2020-05-13 09:42
Sorry I cant test it anymore because its now working again. This is also my experience with this issue in the past. Usually its working after a kodi restart. Just this time it still didnt work after 3 attempts so I thought its actually broken. But opening RCB this morning worked. Dont know what has changed over night

Usually if I get this screen I quit RCB by entering the home button because in the past this was the only way to quit RCB. The "back" button both on my keyboard and my gamepad didnt work. Are there any other ways to quit RCB?

**Comment by maloep** [comment] 2020-05-13 10:55
I use the Esc-Key or Backspace to quit RCB.

Usually RCB should also support the Home-Button but it looks like Kodi has changed the internal Ids that are used for these actions and RCB does not catch all of them. I will try to fix this.

**Comment by Kupo91** [comment] 2020-05-13 11:01
Hm thats weird because Im sure that ESC and Backspace are the first buttons which I tried when this issue occurred for the first time.
Maybe something has changed I will try them if the issue occurs again

**Comment by maloep** [comment] 2020-05-15 21:08
related issue: #420

**Comment by Kupo91** [comment] 2020-07-23 22:13
I just had the chance to test this again. So as I said ESC and backspace doesn't work for me if I'm stuck in this screen. The only way to escape is the home button.
However changing 
`<setting id="rcb_view_mode" default="true"></setting>`
to
`<setting id="rcb_view_mode">50</setting>`
worked well

**Comment by wagnerch** [comment] 2021-03-17 22:20
I have this same problem with Kodi 19, it's reproducible by:
1. opening RCB
2. pressing Home button
3. re-opening RCB
4. the screen is drawn incorrectly, and any navigation results in invalid control id 0.

I don't think there are any Action ID's that can be captured for this, my understanding is pressing Home fires the ActivateWindow built in which closes the existing window without any callback to Python.  And I noticed if you exit normally from the dialog you call self.exit() and it has a bunch of save routines to save various states of the on-screen controls.  Not sure if there is another way, don't really understand this aspect of script plugins.

Using back button to close instead of home, then everything works fine.  It's just a minor annoyance, and usually from 3 above you can just hit back and re-open the addon and everything is fine again.

**Comment by maloep** [comment] 2021-05-21 04:19
Fixed with https://github.com/maloep/romcollectionbrowser/commit/4293d4a0c913ed51a4d525e52a9fb7381ec33694

**Closed by maloep** 2021-05-21 04:19 UTC
Labels: bug
