### ISSUE TITLE
Nintendo Gameboy Advance not scraping game details

### ISSUE THREAD

**Issue by loggin** [maloep/romcollectionbrowser#220] opened 2015-09-02 23:52 UTC
The query to http://thegamesdb.net/api/GetGame.php?name=Bomberman%20Tournament&platform=Nintendo%20Gameboy%20Advance returns an error about the platform it appears to prefer http://thegamesdb.net/api/GetGame.php?name=Bomberman%20Tournament&platform=Nintendo%20Game%20boy%20Advance, I've tweaked resources/lib/config.py within my setup to apply this change and it appears to be scraping now (not gone through the logs to see if other scrapers are working as well  now)

**Comment by bruny** [comment] 2016-06-26 12:14
This was fixed in config.py by commit fe4c35eb1f18d2d87b7f9583860bfef38b0fdd46

**Comment by bruny** [comment] 2016-06-26 12:18
Duplicate of #198

**Closed** 2017-02-23 21:40 UTC
