### ISSUE TITLE
Glitch While Browsing Files on XBMCbuntu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [maloep/romcollectionbrowser#141] opened 2015-04-23 09:16 UTC
```
What steps will reproduce the problem?
This happens anytime a call is made to xbmcgui.Dialog.browse() in XBMCbuntu.

What is the expected output? What do you see instead?
The file browser opens on the left with the default directory of C:/. 
Obviously, this is meaningless in Linux.

What version of the product are you using? On what operating system?
Newest revision on newest Eden release of XBMCbuntu.

Please provide any additional information below.
This one doesn't appear to be your fault, but the XBMC engine thinking it is on 
Windows for a moment. At either rate, it can be fixed on your end by supplying 
a default directory when calling the browser.  For example, I changed line 111 
of wizardconfigxml.py to:

consolePath = dialog.browse(1, 'Path to %s Emulator' %console, 'files', '', 
False, False, '/')

That fixes the issue but obviously will not work on all OS's. A proper default 
directory can be easily supplied.
```

Original issue reported on code.google.com by `rmkr...@gmail.com` on 27 Dec 2012 at 9:52

**Comment by maloep** [comment] 2019-08-10 08:59
Successfully sat this one out. This was already fixed in Kodi. At least, I could not reproduce it anymore.

**Closed by maloep** 2019-08-10 08:59 UTC
Labels: Priority-Low, auto-migrated, bug
