### ISSUE TITLE
Issuing "home" command in XBMC makes RCB un-loadable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [maloep/romcollectionbrowser#179] opened 2015-04-23 09:17 UTC
```
What steps will reproduce the problem?
1. Load up RCB add-on (so list of games is showing)
2. Issue "home" operation on XBMC Remote iOS app (see link below)
3. Attempt to load RCB again

What is the expected output? What do you see instead?
- Nothing happens

What version of the product are you using? On what operating system?
- Lubuntu 14.04.1, XBMC 14.0 Alpha

Official XBMC Remote: 
https://itunes.apple.com/us/app/official-xbmc-remote/id520480364?mt=8
```

Original issue reported on code.google.com by `samh1...@gmail.com` on 4 Aug 2014 at 7:19

**Comment by bruny** [comment] 2016-06-27 10:42
Tested on Isengard 15.2. On Mac, this is the ~/Library/Logs/kodi.log upon RCB load and display list of games:
<snip>
20:37:24 T:123145308819456  NOTICE: RCB_INFO: End onInit
20:37:26 T:123145308819456  NOTICE: RCB_INFO: onAction: 0
20:37:26 T:123145308819456  NOTICE: RCB_INFO: actionId == 0. Input ignored

We then click the Home button on the iOS App, and then try and re-open RCB:
20:37:59 T:123145307209728  NOTICE: Thread BackgroundLoader start, auto delete: false
20:37:59 T:123145307209728  NOTICE: Thread JobWorker start, auto delete: true
20:38:06 T:140735214727168  NOTICE: Previous line repeats 2 times.
20:38:06 T:140735214727168   ERROR: CPythonInvoker(4, /Users/<username>/Library/Application Support/Kodi/addons/script.games.rom.collection.browser/default.py): script didn't stop in 5 seconds - let's kill it
20:38:06 T:123145303453696  NOTICE: Thread LanguageInvoker start, auto delete: false

Looks like we either don't handle the Home event properly, or shutdown is not done gracefully.

**Comment by maloep** [comment] 2018-01-04 18:35
Can't reproduce this issue here. Testing Krypton and Leia on Windows, Home button is backspace.

19:27:06.696 T:9312   DEBUG: CInputManager::OnKey: backspace (0xf008) pressed, action is Back
19:27:06.697 T:7000   DEBUG: RCB_INFO: onAction: 92
19:27:06.697 T:7000   DEBUG: RCB_INFO: onAction: ACTION_CANCEL_DIALOG

Kodi goes to Home screen and RCB can be started again without problems.

In your log above, RCB gets actionid = 0. So there seems to be an issue with kodi reporting the correct action id to scripts. Maybe this has been fixed in recent kodi versions or I need another button to test.

**Comment by maloep** [comment] 2018-01-04 18:58
Ok, backspace wasn't mapped to Home action in my keymap. Using "ActivateWindow(Home)" sends me to the home screen without exiting RCB nicely.

So I added actionid 122 to our cancel actions and it worked as expected.

**Comment by maloep** [comment] 2018-01-04 18:58
Fixed in https://github.com/maloep/romcollectionbrowser/commit/ded95a08b017c1499953b4264f76c5dea217c426

**Closed by maloep** 2018-01-04 18:58 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
