### ISSUE TITLE
 No more Video Preview for Roms and no Logos

### ISSUE THREAD

**Issue by Slipass** [maloep/romcollectionbrowser#305] opened 2017-12-20 22:53 UTC
Hi maloep, i want to say you, that in your version the trailer/ short video preview for the roms does not work. 
In the old version it is possible to setup the path for the movies. In the same location as you can setup the path for the artwork and box pictures. 

The logos are also not displayed. 
I hope it's the right way, otherwise I found no way to write you.

**Comment by maloep** [comment] 2018-01-07 13:57
I could not reproduce this issue. Maybe it was a side effect of other incompatibilities that have been fixed with latest release.

Please test with https://github.com/maloep/romcollectionbrowser/releases/tag/2.1.4 and report back.

**Comment by Slipass** [comment] 2018-01-07 17:04
I can set the settings for the media path again. Super!!!! Thank you very much.

Unfortunately, the Clearlogo view does not yet work. And neither does the scraper.
So I manually downloaded a clear logo for the test and put it in the directory, similar to the videos.
Unfortunately, the logo is not recognized. I've tried all the media paths.


https://i.imgur.com/qicc1z5.jpg
https://i.imgur.com/ziwpe9a.jpg

For this test, i put the file "Super Mario Bros..png" in the path:
....Tools\Emulatoren\NES\Artwork\clearlogos\
and 
....Tools\Emulatoren\NES\Artwork\titles\

The Game/File is called "Super Mario Bros..nes"

Do the logos work for you?
And if so, will they be scrapped by "thegamesdb"?

**Comment by maloep** [comment] 2018-01-07 17:45
Clear logos might be a skin problem. What skin are you using? (I did not know that there are still skins out there that have RCB support. Looks good :)) 

RCBs default skins don't support clear logos at all, neither do the scrapers. This might be an option for later as thegamesdb provides this artwork type.

Title artwork in RCB means screenshots of the game title, not the title as clearlogo.

**Comment by Slipass** [comment] 2018-01-07 19:00
So, thanks for the advice:)

I use Aeon Madnox. 
I could send you the rcb. xml from the 1080i directory if you have time and desire?
I can't program and maybe only a small line/part in the .xml is missing?

I think I've seen Madnox support Clearlogos on RCB.

I could do the testing if you want to try it?

**Comment by maloep** [comment] 2018-01-08 06:04
Thanks.

What Kodi version are you using? If I found the correct repositories there haven't been any changes for Krypton and below since 2 years:
https://github.com/mikesilvo164/skin.aeon.madnox/tree/krypton/1080i

For Leia there have been some changes but nothing crucial. Just some positioning etc.:
https://github.com/mikesilvo164/skin.aeon.madnox/commits/leia/1080i/script-Rom_Collection_Browser-main.xml

Are you sure there has been support for clearlogos? I can't imagine from what I have seen.

**Comment by Slipass** [comment] 2018-01-08 08:04
Currently I still use the version 17.6, because version 18 still has too many bugs. 
I'm currently testing version 18 together with Madnox.

The repositories are correct.

Whether the logos are really visible, I can not say 100%.
I mean, it's on a screenshot, but I hope I do not put my hand on fire.

**Comment by maloep** [comment] 2018-02-01 17:06
Video preview is fixed. Clearlogo support will be handled in https://github.com/maloep/romcollectionbrowser/issues/334

**Closed by maloep** 2018-02-01 17:06 UTC
