### ISSUE TITLE
'module' object has no attribute 'localize'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [maloep/romcollectionbrowser#184] opened 2015-04-23 09:17 UTC
```
What steps will reproduce the problem?
1. When i open XBMC i received the error 'module' object has no attribute 
'localize'
2. When i install it using the platform_libraries.zip i received another error 
name 'Logutil' is not defined

What is the expected output? What do you see instead?
All other add-ons, programs, script etc are working perfectly. The only issue i 
have is this.

What version of the product are you using? On what operating system?
I am using latest stable XBMC 13.2 on Windows 8.1

Please provide any additional information below.

Please help me to solve this issue. Never had it before, only when i format my 
pc and re-install everything.
```

Original issue reported on code.google.com by `xyda...@gmail.com` on 18 Sep 2014 at 5:48

**Comment by bruny** [comment] 2016-06-27 10:44
Possible duplicate of #178

**Closed** 2018-01-03 14:18 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
