### ISSUE TITLE
"dummyGUI instance has no attribute 'xbmcversionNo'"

### ISSUE THREAD

**Issue by Kenoux** [maloep/romcollectionbrowser#222] opened 2016-02-28 02:28 UTC
Hi Malte,

Error message when we launch windows game on Aeon MQ 5 or Aeon MQ6 from widget screen.

" dummyGUI instance has no attribute 'xbmcversionNo' "

and game doesn't start..

Without this message it's perfect. 

Thanks for your works, I hope you can provide a fix since 6 months.

2015-03-19 07:28 Post: #4727
ragedogg69 Wrote:
Is anyone using RCB with MQ5? While games launch fine from inside RCB, they do not launch from the most played shortcut list within MQ5. Anyone else have the issue?

"dummyGUI instance has no attribute 'xbmcversionNo'"

**Comment by bruny** [comment] 2016-07-17 12:39
Need more info on how to reproduce this so I can verify a fix, but I suspect the cause is that when creating a DummyGUI instance (instead of the normal UIGameDB in gui.py), we are not setting the xbmcversionNo attribute as UIGameDB does.

The fix should be adding the same code in dummyGUI's init() method in default.py:

`xbmcversion = xbmcaddon.Addon('xbmc.addon').getAddonInfo('version')
Logutil.log("XBMC version = " +xbmcversion, util.LOG_LEVEL_INFO)
	
xbmcversionNo = xbmcversion[0:2]
Logutil.log("XBMC major version no = " +xbmcversionNo, util.LOG_LEVEL_INFO)`

**Comment by Kenoux** [comment] 2016-07-18 13:51
Hi Bruny 

Thanks to take your time for this issue.

To reproduce this issue you need to have: 

1-Aeon MQ6* at main theme  on a Windows OS **

*(Aeon MQ6 install RCB by default normally) 
**(error appear from Windows 7 to windows 10)

2-Activate widget on main menu for game/RCB part*.

*On main menu you need to use up down key to let appear menu below (link).
https://googledrive.com/host/0B-9ewpmLdTHqYkhKWFZONGNpcTA

This menu allow you to add widget on part you want example add latest movies seen when you go on menu movie...

3-You need to add an "IBM PC compatible" collection into RCB (PC game)*

*To do that you can use LNK shortcut as ROM...

4-Launch a game from your collection "IBM PC Compatible"

5- After launching the game*, you go on main menu into KODI and if you have activated widget for game you will see your game on main menu (as you see latest series or movies)

*You need to launch your game multiple times because I'don't know why he doesn't appear the first time (Widget is here to launch you favorites game and don't force you to search your games into all the collection so there is maybe a count to let it appear into widget mode) 

6-When you have your game on widget menu and you try to launch it directly through widget menu you have the error 

                     "dummyGUI instance has no attribute 'xbmcversionNo'".

the game doesn't launch...

This issue appear only for "IBM pc compatible" game, for "SNES", "SEGA", "WII" everything work when you launch it through widget menu..

I hope i've been clear with my explanation, I don't know how to add screenshots or files but if you need it i can sent that to you.

Thanks again for your works Bruny!

**Comment by bruny** [comment] 2016-07-19 14:21
Can you try editing the file default.py (on Windows, I believe this is somewhere under %APPDATA%\kodi\addons\script.games.rom.collection.browser), changing:

```
class dummyGUI():
	useRCBService = True
	player = xbmc.Player()
```
to:

```
class dummyGUI():
	useRCBService = True
	player = xbmc.Player()

	xbmcversion = xbmcaddon.Addon('xbmc.addon').getAddonInfo('version')
	xbmcversionNo = xbmcversion[0:2]
```
Note there is one tab, not four spaces, as the indent.

If that works, I can create a PR with the fix.

**Comment by Kenoux** [comment] 2016-07-20 17:17
Hi Bury,

Nice job !!

I try your fix and it work fine (I cheked on multiple installation).

It's perfect !

Thanks for your help and your work !

**Comment by bruny** [comment] 2017-03-18 11:12
PR merged. Closing.

**Closed by bruny** 2017-03-18 11:12 UTC
