### ISSUE TITLE
Prevent Cmd window to pop up when loadin

### ISSUE THREAD

**Issue by GoogleCodeExporter** [maloep/romcollectionbrowser#210] opened 2015-04-23 09:17 UTC
```
Please enter detailed request description

```

Original issue reported on code.google.com by `Mediu...@googlemail.com` on 22 Mar 2015 at 10:30

**Comment by bruny** [comment] 2017-02-24 10:49
Closed as duplicate of #211

**Closed by bruny** 2017-02-24 10:49 UTC
Labels: auto-migrated, Priority-Medium, Type-Enhancement
