### ISSUE TITLE
Allow other initial view then "Info Boxart"

### ISSUE THREAD

**Issue by bell07** [maloep/romcollectionbrowser#399] opened 2019-04-03 14:50 UTC
I like more the "Info List" view. But if I leave the add-on and start again, the view is back to "Info Boxart". Tested with current 2.2.3
My feature request is to save the current view so I get the same view if the app is restarted. Alternativelly a setting for the default view.

**Comment by Kupo91** [comment] 2019-04-03 15:13
Its a bug https://github.com/maloep/romcollectionbrowser/issues/393

**Comment by Royusmc** [comment] 2019-04-04 17:57
If you know how to change a text doc you can use this workaround. Go here kodi\addons\script.games.rom.collection.browser\resources\skins\Default\720p\script-Rom_Collection_Browser-main.xml. Open it with any text editor and change line 10 and maybe line 4. On line 10 <views>50,52,53,57,58,59</views> change it to <views>57,50,52,53,58,59</views> and if needed change line 4 from <defaultcontrol always="false">50</defaultcontrol> to <defaultcontrol always="false">57</defaultcontrol>. If this is the wrong view just change 57 to the one you want. Also this location is for the default skin if your using any other skin make changes there instead. Good luck.

**Comment by bell07** [comment] 2019-04-05 04:16
I changed the both lines as proposed, but no change in behaviour. THe "Info Boxart" is still used by default. Maybe the current setting is saved in any other file?

**Comment by bell07** [comment] 2019-04-05 05:47
Changing to "52" in Confluence Skin folder, instead of "Default", did the trick. Now the workaround works for me. Thank you.

**Comment by Royusmc** [comment] 2019-04-08 15:37
I thought you would want to know. If someone knows how to add this to the real code after checking that it works that would be great. Thanks for any help.


Ok it took forever but I did find a fix and I just wanted to share.
 In location
 kodi\addons\script.games.rom.collection.browser\resources\lib\gui.py
 Just change this

 #reset view mode
 viewModeId = self.Settings.getSetting(util.SETTING_RCB_VIEW_MODE)
 if viewModeId != None and viewModeId != '':
 xbmc.executebuiltin("Container.SetViewMode(%i)" % int(viewModeId))

 To this

 #reset view mode
 viewModeId = self.Settings.getSetting(util.SETTING_RCB_VIEW_MODE)
 if viewModeId != None and viewModeId != '':
 xbmc.executebuiltin("Container.SetViewMode(%i)" % int(viewModeId))
 xbmc.executebuiltin("Container.SetViewMode(%i)" % int(viewModeId))
 
I know this should not work but give it a try. Just Doubling that line got it to work for me.
 I hope this helps someone. Good luck

**Comment by maloep** [comment] 2019-07-31 15:02
Duplicate of #393

**Closed by maloep** 2019-07-31 15:02 UTC
